# Generated by Django 4.2 on 2023-05-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('ts', models.IntegerField()),
                ('event', models.CharField(max_length=30)),
                ('msg', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('ts', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('clicks', models.TextField(blank=True)),
                ('opens', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('ts', models.IntegerField()),
                ('event', models.CharField(max_length=30)),
                ('ip', models.CharField(blank=True, max_length=46)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('msg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emailhooks.openmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
